add toolchain

diff --git a/.github/workflows/build-openwrt.yml b/.github/workflows/build-openwrt.yml
--- a/.github/workflows/build-openwrt.yml
+++ b/.github/workflows/build-openwrt.yml
@@ -83,7 +83,25 @@ jobs:
         ccache: 'true'
         prefix: ${{ github.workspace }}/openwrt
         clean: ${{ github.event.inputs.clean_cache }}
-        
+    
+    - name: Download toolchain
+      run: |
+        cd openwrt
+        set -e
+        # 先尝试下载 sha256sums 文件
+        if ! curl -sfL https://downloads.immortalwrt.org/releases/${REPO_TAG#v}/targets/x86/64/sha256sums -o sha256sums; then
+          echo "sha256sums file download failed"
+          exit 0
+        fi
+        TOOLCHAIN_FILENAME=$(grep toolchain sha256sums | awk '{print $2}' | sed 's/^\*//')
+        if [ -z "$TOOLCHAIN_FILENAME" ]; then
+          echo "no toolchain file found"
+          exit 0
+        fi
+        curl -sfL https://downloads.immortalwrt.org/releases/${REPO_TAG#v}/targets/x86/64/$TOOLCHAIN_FILENAME -o toolchain.tar.zst
+        tar -I zstd -xf toolchain.tar.zst
+        rm -f toolchain.tar.zst sha256sums
+
     - name: Load custom feeds
       run: |
         [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
